/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package psosimulation

import processing.core.PApplet

fun main() {
    val psoDrawer = PSODrawer()
    psoDrawer.targetFunction.function = { x, y -> psoDrawer.noise(x * 0.02f, y * 0.02f) * 360f }

    PApplet.runSketch(arrayOf("PSODrawer"), psoDrawer)
}
